Added get all music and content music by id
backdorJ/Russian-Spotify pull request #24
Opened 2024-04-01 16:22 UTC by backdorJ

2024-04-01 16:25 UTC, fuz1kort approved these changes

2024-04-01 16:26 UTC, s1ches approved these changes
Это четко

2024-04-01 19:13 UTC, irekkkarimov approved these changes

2024-04-01 19:13 UTC, irekkkarimov commented on RussianSpotify.API/RussianSpotify.API.Contracts/Models/IPaginationFilter.cs
> +public interface IPaginationFilter
документация

2024-04-01 19:23 UTC, irekkkarimov requested changes

2024-04-01 19:23 UTC, irekkkarimov commented on RussianSpotify.API/RussianSpotify.API.WEB/Controllers/SongController.cs
> +                request is null
двойная проверка на null?

2024-04-01 21:09 UTC, backdorJ commented on RussianSpotify.API/RussianSpotify.API.WEB/Controllers/SongController.cs
> +                request is null
да

2024-04-02 10:58 UTC, irekkkarimov approved these changes

2024-04-02 11:02 UTC, merged