Feature/adaptive accountpage
backdorJ/Russian-Spotify pull request #29
Opened 2024-04-08 08:16 UTC by fuz1kort

Добавил адаптив
Поправил информацию о подписке

2024-04-08 08:27 UTC, irekkkarimov requested changes

2024-04-08 08:27 UTC, irekkkarimov commented on spotify-react-app/src/pages/AccountPage/AccountPage.tsx
> +                                <p className="nickname">Irek</p>
Хардкор, бери с юзера никнейм

2024-04-08 08:27 UTC, irekkkarimov commented on spotify-react-app/src/pages/AccountPage/AccountPage.tsx
> +                                <p className="nickname">Irek</p>
Типа почему два никнейма, второй хардкод

2024-04-08 16:19 UTC, fuz1kort commented on spotify-react-app/src/pages/AccountPage/AccountPage.tsx
> +                                <p className="nickname">Irek</p>
а ой, не убрал, ща

2024-04-09 10:45 UTC, backdorJ approved these changes

2024-04-09 10:55 UTC, irekkkarimov approved these changes

2024-04-09 15:05 UTC, s1ches approved these changes

2024-04-09 15:05 UTC, merged