Feature/create login register page
backdorJ/Russian-Spotify pull request #5
Opened 2024-03-13 14:41 UTC by fuz1kort

Сделал LoginPage и RegisterPage(вёрстка со стилями, адаптив, анимации)

2024-03-13 16:58 UTC, irekkkarimov requested changes

2024-03-13 16:58 UTC, irekkkarimov commented on spotify-react-app/src/commonComponents/Header/Header.tsx
> +                    <path id="Vector"
Уверен что красиво так делать? (Если никак иначе, то ок). Мб можно как-то в файл вынести svg или чет такое

2024-03-13 16:58 UTC, irekkkarimov commented on spotify-react-app/src/pages/LoginPage/components/AuthForm/AuthForm.tsx
> +                            <path
выше

2024-03-13 16:58 UTC, irekkkarimov commented on spotify-react-app/src/pages/RegisterPage/components/InputRegisterWidget/InputRegisterWidget.tsx
> +        setIsPassword1Visible(!isPassword1Visible);
в такие случаи можно делать setIsPasswordVisible(prev => !prev). Необязательно, но мне кажется так правильнее в каком-то плане. На будущее

2024-03-13 16:58 UTC, irekkkarimov commented on spotify-react-app/src/pages/RegisterPage/components/InputRegisterWidget/InputRegisterWidget.tsx
> +            {
Зачем фигурные скобки?

2024-03-14 08:15 UTC, fuz1kort commented on spotify-react-app/src/commonComponents/Header/Header.tsx
> +                    <path id="Vector"
не хотят так работать

2024-03-14 08:17 UTC, fuz1kort commented on spotify-react-app/src/pages/RegisterPage/components/InputRegisterWidget/InputRegisterWidget.tsx
> +            {
забыл убрать, исправил

2024-03-14 08:17 UTC, fuz1kort commented on spotify-react-app/src/pages/RegisterPage/components/InputRegisterWidget/InputRegisterWidget.tsx
> +        setIsPassword1Visible(!isPassword1Visible);
окей

2024-03-15 09:08 UTC, irekkkarimov approved these changes

2024-03-15 11:03 UTC, fuz1kort commented on spotify-react-app/src/commonComponents/Header/Header.tsx
> +                    <path id="Vector"
исправил

2024-03-15 11:03 UTC, fuz1kort commented on spotify-react-app/src/pages/LoginPage/components/AuthForm/AuthForm.tsx
> +                            <path
исправил

2024-03-15 13:27 UTC, s1ches approved these changes

2024-03-15 16:27 UTC, backdorJ approved these changes

2024-03-16 05:34 UTC, merged